name: CI Inventario

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    name: Backend - Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Instalar dependencias backend
        run: npm ci

      - name: Ejecutar pruebas backend
        run: npm test

  frontend:
    name: Frontend - Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Instalar dependencias frontend
        run: npm ci

      - name: Ejecutar pruebas frontend
        run: npm test -- --run
